<template>
    <div class="insurance">
        <p>ISSUED BY LEAD BANK | 2023 © ATLAS EXPLORATION, INC.</p>
        <p>
            ATLAS EXPLORATION, INC IS A TECHNOLOGY COMPANY, NOT A BANK. ATLAS CARD IS ISSUED BY LEAD BANK
            ("ISSUER"). AN APPLICATION IS REQUIRED. CARDHOLDERS MUST BE AT LEAST 18 YEARS OLD AND A
            CITIZEN OF THE UNITED STATES, OR A PERMANENT RESIDENT WITH A VALID SOCIAL SECURITY NUMBER
            (SSN) OR ITIN. FINANCING IS SUBJECT TO ISSUER'S APPROVAL. PAYMENT OF ACCOUNT BALANCE DUE IN
            FULL MONTHLY. FEES MAY BE ASSESSED ON OVERDUE AMOUNTS. AN ANNUAL MEMBERSHIP FEE APPLIES.
        </p>
    </div>
</template>